[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sleep_in = "GL2sKpP9JxLxcGofPiPDvGKXi9TtUEVBFAUFJmzqoQNY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yavuz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
